include:linux: add missing part from commit 714f0473216382cd6334745d4c36cc71d0fd0977
*fix complile time error with pwrutilx cpu governor

../drivers/cpufreq/cpufreq.c:1094:9: error: use of undeclared identifier 'CPUFREQ_DEFAULT_GOVERNOR'
                gov = CPUFREQ_DEFAULT_GOVERNOR;
                      ^